name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Server Dependencies
        run: npm installed

      - name: Execute tests
        run: npm run test 

  deploy_server:
    if: needs.run_tests.result == 'success' && github.ref == 'refs/heads/main'
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Server
        env:
          SERVER_DEPLOY_URL: ${{ secrets.SERVER_DEPLOY_URL }}
        run: |
          curl -X POST $SERVER_DEPLOY_URL -F "artifact=@server/build"